name: "Scully Publish"
description: "Build and deploy your Scully site to GitHub Pages."
branding:
  icon: "book-open"
  color: "red"
inputs:
  access-token:
    description: "A personal access token needed to push your site after it has been built."
    required: true
  deploy-branch:
    description: "The branch expected by GitHub to have the static files needed for your site."
    required: false
    default: "master"
  build-args:
    description: "Additional arguments that get passed to `npm run build`."
    required: false
    default: ""
  scully-args:
    description: "Additional arguments that get passed to `npm run scully`."
    required: false
    default: ""
runs:
  using: composite
  steps:
    - run: "curl -fsSL https://fnm.vercel.app/install | bash"
      shell: bash
    - run: "cat fnm.txt >> /home/runner/.bashrc"
      shell: bash
    - run: "source /home/runner/.bashrc"
      shell: bash
    - run: "fnm install 14 && fnm use 14"
      shell: bash
    - run: "node index.js"
      shell: bash
